### ISSUE TITLE
.prm file about Fig.13

### ISSUE THREAD

**Issue by shaohuiliu-github** [heronphi/Heron_Super22#1]
Dear Dr.Philip Heron,

I'm a beginner about ASPECT, and I'm very interested in your recent work.
I'd like to learn ASPECT by your .prm file. But I found that there is no 3D model .prm file about Fig.13 (Paper: The role of subduction in the formation of Pangean oceanic large igneous provinces).
If it is possible, could you please upload the 3D model .prm file about your article?

Best wishes,
Shaohui Liu

**Comment by heronphi** [comment]
Hi Shaohui, Sorry about that - the 3D model input has been uploaded. However, by adding a third dimension to Model 6 would work as well. Thanks for reaching out! Phil

**Comment by shaohuiliu-github** [comment]
> 
Dear Dr.Philip Heron

Thank you very very much!  
Your work is so good, and I really want to do my work like yours. 
And you are really kind to new learners~

I am a pre-admission doctoral student in the Institute of Geology and Geophysics, Chinese Academy of Sciences. 
And my future work is about 3D Earth with data assimilation. I will try my best in the future! 

Best wishes,
Shaohui Liu

**Comment by heronphi** [comment]
Hi Shaohui, 

No problem! Good luck with your work - please reach out if you would like to collaborate! 

Take care, 

Phil
